### ISSUE TITLE
Major Bug - Helicopter Crashes on take off

### ISSUE THREAD

**Issue by TrshPndaa** [flashyonthat/bgrp-tracker#7] opened 2024-07-18 16:05 UTC
Helicopters will crash on take off, ive tried it on two helicopters and issue persists, may also apply to jets but i dont know

**Comment by QuantumOctopusCipher** [comment] 2024-07-24 04:34
Duplicate of https://github.com/flashyonthat/bgrp-tracker/issues/8

**Closed as not planned by QuantumOctopusCipher** 2024-07-24 04:34 UTC
